### ISSUE TITLE
Return Error Rather than Panic

### ISSUE THREAD

**Issue by briandowns** [gorhill/cronexpr#10]
Would it be possible to change the cronexpr.MustParse() function to return an error rather than panic?  If so, I'll gladly submit a PR.  Thanks!

**Comment by gorhill** [comment]
That's what [`cronexpr.Parse()`](https://github.com/gorhill/cronexpr/blob/master/cronexpr.go#L69) does. `cronexpr.MustParse()` is for when one know the cron expression is valid.

**Comment by briandowns** [comment]
Damn... I should have read more of the issues filed but more so the docs. :D  Thanks for the quick response!
