### ISSUE TITLE
doesnt work in parallel usage (multiple goroutines)

### ISSUE THREAD

**Issue by rhaps107** [gorhill/cronexpr#26]
In parsing, global package variable layoutRegexp is changing. It is map, so usage in multiple gorountines causes map concurrent write error.

**Comment by gorhill** [comment]
Is there a written rule out there that **all** packages must be concurrency-safe?

**Comment by s7v7nislands** [comment]
so when using this package, I can't using goroutine?

**Comment by hus787** [comment]
@gorhill I suppose so else Golang doesn't guarantee anything.

Ref: https://github.com/golang/go/issues/13446#issuecomment-161104226
